### PR TITLE
Start Implementing Receiver and Switch to PC6 for RX

### PR DESCRIPTION
**Pull request by piparocj**
I essentially made a basic skeleton for the receiver. Additionally, since we want to use input capture, we have to use a GPIO pin that is connected to a timer. In the case of TIM3, it has channel 2 connected to PC6. I switched RX to use that instead then. I have not tested it and I won't have time this weekend because I'm doing the 24-hour programming competition.

If you have time, would you be able to make sure the channel monitor and transmitter still works? If not, I can test it on Sunday.

Additionally, in the future, I would like to clean up some of this code, but I basically copied what was in there before for time's sake.

### CODE REVIEW

**Comment by larsonma** [comment]
I'll review and test this weekend. I plan on working on the receiver on Sunday.

**Comment by piparocj** [comment]
I had time to test at least the channel monitor part right now. The last commit got it working properly. I don't think the transmitter will be affected but I will try to test it anyway.

**Comment by piparocj** [comment]
I did test the transmitter following our test plan. Everything is working great. Feel free to test it yourself!

**Review by larsonma — APPROVED** [review]
looks good!

**Pull request merged**
